name: C:\Anaconda3\envs\py3k_jira
dependencies:
- django=1.9.5=py34_0
- ipython=4.2.0=py34_0
- nose=1.3.7=py34_0
- pip=8.1.1=py34_1
- python=3.4.4=4
- setuptools=20.7.0=py34_0
- pip:
  - gunicorn==19.5.0
  - jira==1.0.3
  - stashy==0.1.1

